# Rename the project and update the description for your project
name: rvpodhooks
description: "Riverpod Hooks, GoRouter and ResponsiveFramework"
publish_to: "none"
version: 0.1.0

# Update the SDK version to the latest stable version
environment:
  sdk: ">=3.5.0 <4.0.0"

# Core Dependencies: (add/update using pubspec assist)
#
# hooks_riverpod,flutter_hooks,go_router,responsive_framework,intl,animations,json_annotation,freezed_annotation,http,shared_preferences,vector_graphics,dartx,web
#
dependencies:
  animations: ^2.0.11
  dartx: ^1.2.0
  exposed:
    git: https://github.com/Hasuki69/exposed.git
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  responsive_framework: ^1.5.1
  shared_preferences: ^2.3.2
  vector_graphics: ^1.1.11+1
  web: ^1.0.0

# Core Dev Dependencies: (add/update using pubspec assist)
#
# build_runner,custom_lint,flutter_lints,freezed,json_serializable,riverpod_lint,vector_graphics_compiler
#
dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.13
  vector_graphics_compiler: ^1.1.11+1

# Assets and Fonts
# Modify the assets and fonts section to match your project's assets and fonts
#
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/svgs/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
